spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

